
apiVersion: v1
kind: Deployment
metadata:
  labels:
    run: node-expressjs-sample
  name: node-expressjs-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      run: node-expressjs-sample
  template:
    metadata:
      labels:
        run: node-expressjs-sample
    spec:
      containers:
      - image: ${IMAGE}
        name: app

---    

apiVersion: v1
kind: Service
metadata:
  name: node-expressjs-sample
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    run: node-expressjs-sample
  sessionAffinity: None
  type: ClusterIP
